# Generated by Django 5.0.6 on 2024-07-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_produit_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='disponibilte',
            new_name='disponibilite',
        ),
    ]
